name: sockboom check-in script

on:
  push:
    branches:
      - main
  schedule:
    - cron: "30 11 * * *"

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: 'Install requirements'
      run: pip3 install requests
    - name: Run sockboom check-in script
      env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWD: ${{ secrets.PASSWD }}
      run:
        python3 checkin.py
